title: Cesta roverským věkem
baseURL: https://gracious-kalam-e9c5ec.netlify.com/
languageCode: cs-cz
googleanalytics: UA-139325404-1
publishDir: public



menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Description of my new site.
  authors: Authors

