title: Cesta roverským věkem
baseURL: https://gracious-kalam-e9c5ec.netlify.com/
languageCode: cs-cz
googleanalytics: UA-139325404-1
publishDir: public



menu:
  main:
    - name: Domů
      url: /
      weight: 10
    - name: Archiv
      identifier: post
      url: /post/
      weight: 20

params:
  description: 
  authors: Hermiona & Hanka & Ráca

